### ISSUE TITLE
Error in Ops.data.frame(guide_loc, panel_loc) :    ‘==’ only defined for equally-sized data frames

### ISSUE THREAD

**Issue by PandaPowell** [jrs95/geni.plots#2]
Hi,

Thanks for making such a useful package avaliable! I have been using gassocplot2 for a while.

When I run the fig_region function, I recieve the following error:

Error in Ops.data.frame(guide_loc, panel_loc) :    ‘==’ only defined for equally-sized data frames

The length of the dataframe and ld matrix are the same, in the same order.

guide_loc and panel loc are not defined within the fig_region function so I am not sure how to pinpoint what is causing the error.

Any help would be greatly appreciated.

Thanks!

**Comment by PandaPowell** [comment]
I forgot to add the same error is presented when I run the example from the vignette:

[fig_region](https://jrs95.github.io/geni.plots/reference/fig_region.html)(
  data = geni.plots::[geni_test_region](https://jrs95.github.io/geni.plots/reference/geni_test_region.html)$assoc,
  corr = geni.plots::[geni_test_region](https://jrs95.github.io/geni.plots/reference/geni_test_region.html)$corr,
  build = 37
)

Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames

**Comment by jrs95** [comment]
Hi Sam,

Thanks for using `geni.plots`.

Can you tell me which version of R and `ggplot2` and `patchwork` packages you are using? This error appears to be an issue relating to the interplay between the `ggplot2` (which has undergone some backend changes) and `patchwork` packages, see here: [#5612](https://github.com/tidyverse/ggplot2/issues/5612). I think your problem will be solved by updating both packages to their latest CRAN versions.

Best wishes,

James

**Comment by PandaPowell** [comment]
Hey James, You're right updating the packages solved this error. Thanks a lot for the quick solution.
