### ISSUE TITLE
Error when running fig_region and fig_region_stack

### ISSUE THREAD

**Issue by david-ds3938** [jrs95/geni.plots#3]
Hi James,

Long time user of gassocplot and gassocplot.  Getting the below error with the fig_region and fig_region_stack functions from the geni.plots package:

Error in Ops.data.frame(guide_loc, panel_loc) : 
  ‘==’ only defined for equally-sized data frames

I get this same error when I run the code for these two functions in your vignette as well.  All the other figures work as advertised.

Cheers,
David

**Comment by jrs95** [comment]
Hi David,

Thanks for using the `gassocplot` packages and now `geni.plots`.

This error is resolved by updating the `ggplot2` and `patchwork` packages to the latest CRAN releases. See [here](https://github.com/jrs95/geni.plots/issues/2) for further details.

Best wishes,

James

**Comment by david-ds3938** [comment]
Hi James,

Thanks for this – that got it!  Rookie error…

Cheers,
David
