### ISSUE TITLE
Error: chromosomes have to either be autosomal or sex 

### ISSUE THREAD

**Issue by fangzhoufan** [jrs95/geni.plots#4]
fig_m3<-fig_manhattan(
+   data = geni_ff,
+   block_thresh = 5e-8,
+   label_box = T,
+   title='Flat Foot'
+ )+my_theme
Error in fig_manhattan(data = geni_ff, block_thresh = 5e-08, label_box = T,  : 
  chromosomes have to either be autosomal or sex
How do I solve this problem? Should I delete the 23,24 representative chromosomes from my dataset but I don't think that's OK

**Comment by jrs95** [comment]
Hi Fan,

I think you just need to change 23 and 24 to X and Y in your dataset.

Best wishes,

James
